source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'QBFlatButton'
pod 'TOWebViewController'
pod 'SCLAlertView-Objective-C'
pod 'Google/Analytics'
pod 'Google/AppInvite'
pod 'SARate'
