submission_information({
    export_compliance: {
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_uses_encryption: false,
    }
})

automatic_release(true)