output_directory("./screenshots")
clear_previous_screenshots(true)
override_status_bar(true)


# Uncomment the lines below you want to change by removing the # in the beginning

# How to update this list:
#  1. devices(["bobcat"])
#  2. Run `fastlane snapshot`
#  3. Check the output for the list of devices
#
# Got this list using:
# https://github.com/search?q=path%3A**%2FSnapfile+15&type=code&ref=advsearch
# See what others do then update to latest devices and an iOS version that I support
# And maybe check for this iOS version like https://support.apple.com/guide/iphone/iphone-models-compatible-with-ios-17-iphe3fa5df43/ios
# Also see https://appstoreconnect.apple.com/apps/784258202/distribution/ios/version/inflight for what sizes are required
devices([
    "iPhone 15 Pro Max", # 6.7-inch
    # None of the available devices are 6.5-inch
    # None of the available devices are 5.4-inch
    "iPad Pro (12.9-inch) (6th generation)", # 12.9-inch
    "iPad Pro (11-inch) (4th generation)", # 11-inch
])

# Got this list using:
# find . | grep 'lproj$' | sed 's/.*\///' | sed 's/.lproj//' | sort | uniq
# Last updated 2024-03-10
languages([
    ["en", "en_US"],
])

# The name of the scheme which contains the UI Tests
# scheme("SchemeName")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
